<a href="https://colab.research.google.com/github/as9786/ComputerVision/blob/main/ImageGeneration/code/PixelCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tqdm import tqdm

# Dataset

In [2]:
num_classes = 10
input_shape = (28,28,1)
n_residual_blocks = 5
(x,_),(y,_) = keras.datasets.mnist.load_data()
data = np.concatenate((x,y),axis=0)
# 0과 1의 값을 갖도록 정규화화
data = np.where(data < (0.33 * 256),0,1)
data = data.astype(np.float32)

11490434/11490434 [==============================] - 2s 0us/step


# Model

In [3]:
class PixelConvLayer(layers.Layer):
  def __init__(self,mask_type,**kwargs):
    super().__init__()
    self.mask_type = mask_type
    self.conv = layers.Conv2D(**kwargs)

  def build(self,input_shape):
    self.conv.build(input_shape)
    kernel_shape = self.conv.kernel.get_shape()
    self.mask = np.zeros(shape=kernel_shape)
    self.mask[:kernel_shape[0]//2,...] = 1.0
    self.mask[kernel_shape[0]//2,:kernel_shape[1]//2,...] = 1.0
    if self.mask_type=='B':
      self.mask[kernel_shape[0]//2,kernel_shape[1]//2,...] = 1.0
  
  def call(self,inputs):
    self.conv.kernel.assign(self.conv.kernel*self.mask)
    return self.conv(inputs)

In [10]:
example_kernel = np.zeros((3,3))
example_kernel

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# Mask A
example_kernel[:3//2,...] = 1.
example_kernel[3//2,:3//2,...]=1.
example_kernel

array([[1., 1., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Mask B
example_kernel[3//2,3//2,...] = 1
example_kernel

array([[1., 1., 1.],
       [1., 1., 0.],
       [0., 0., 0.]])

In [4]:
class ResidualBlock(layers.Layer):
  def __init__(self,filters,**kwargs):
    super().__init__(**kwargs)
    self.conv1 = layers.Conv2D(filters=filters,kernel_size=1,activation='relu')
    self.pixel_conv = PixelConvLayer(
        mask_type = 'B',
        filters=filters//2,
        kernel_size=3,
        activation='relu',
        padding='same'
    )
    self.conv2 = keras.layers.Conv2D(filters=filters,kernel_size=1,activation='relu')

  def call(self,inputs):
    x = self.conv1(inputs)
    x = self.pixel_conv(x)
    x = self.conv2(x)
    return layers.add([inputs,x])

In [5]:
inputs = keras.Input(shape=input_shape)
x = PixelConvLayer(mask_type='A',filters=128,kernel_size=7,activation='relu',padding='same')(inputs)

for _ in range(n_residual_blocks):
  x = ResidualBlock(filters=128)(x)

for _ in range(2):
  x = PixelConvLayer(
      mask_type='B',
      filters = 128,
      kernel_size=1,
      strides=1,
      activation='relu',
      padding='valid'
  )(x)

out = layers.Conv2D(filters=1,kernel_size=1,strides=1,activation='sigmoid',padding='valid')(x)

In [6]:
pixel_cnn = keras.Model(inputs,out)
adam = keras.optimizers.Adam(learning_rate = 0.0005)
pixel_cnn.compile(optimizer=adam,loss='binary_crossentropy')
pixel_cnn.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 28, 28, 1)]       0         
                                                                 
 pixel_conv_layer (PixelConv  (None, 28, 28, 128)      6400      
 Layer)                                                          
                                                                 
 residual_block (ResidualBlo  (None, 28, 28, 128)      98624     
 ck)                                                             
                                                                 
 residual_block_1 (ResidualB  (None, 28, 28, 128)      98624     
 lock)                                                           
                                                                 
 residual_block_2 (ResidualB  (None, 28, 28, 128)      98624     
 lock)                                                       

In [14]:
pixel_cnn.fit(x=data,y=data,batch_size=128,epochs=50,validation_split=0.1,verbose=2)

Epoch 1/50
493/493 - 53s - loss: 0.1132 - val_loss: 0.0927 - 53s/epoch - 107ms/step
Epoch 2/50
493/493 - 51s - loss: 0.0912 - val_loss: 0.0898 - 51s/epoch - 104ms/step
Epoch 3/50
493/493 - 52s - loss: 0.0891 - val_loss: 0.0885 - 52s/epoch - 105ms/step
Epoch 4/50
493/493 - 51s - loss: 0.0880 - val_loss: 0.0880 - 51s/epoch - 104ms/step
Epoch 5/50
493/493 - 51s - loss: 0.0871 - val_loss: 0.0868 - 51s/epoch - 104ms/step
Epoch 6/50
493/493 - 52s - loss: 0.0866 - val_loss: 0.0872 - 52s/epoch - 105ms/step
Epoch 7/50
493/493 - 51s - loss: 0.0862 - val_loss: 0.0860 - 51s/epoch - 104ms/step
Epoch 8/50
493/493 - 51s - loss: 0.0858 - val_loss: 0.0859 - 51s/epoch - 104ms/step
Epoch 9/50
493/493 - 51s - loss: 0.0854 - val_loss: 0.0855 - 51s/epoch - 104ms/step
Epoch 10/50
493/493 - 51s - loss: 0.0852 - val_loss: 0.0852 - 51s/epoch - 104ms/step
Epoch 11/50
493/493 - 52s - loss: 0.0849 - val_loss: 0.0849 - 52s/epoch - 105ms/step
Epoch 12/50
493/493 - 51s - loss: 0.0847 - val_loss: 0.0849 - 51s/epoch - 

# Infer

In [15]:
from IPython.display import Image, display

# Create an empty array of pixels.
batch = 4
pixels = np.zeros(shape=(batch,) + (pixel_cnn.input_shape)[1:])
batch, rows, cols, channels = pixels.shape

# Iterate over the pixels because generation has to be done sequentially pixel by pixel.
for row in tqdm(range(rows)):
    for col in range(cols):
        for channel in range(channels):
            # Feed the whole array and retrieving the pixel value probabilities for the next
            # pixel.
            probs = pixel_cnn.predict(pixels)[:, row, col, channel]
            # Use the probabilities to pick pixel values and append the values to the image
            # frame.
            pixels[:, row, col, channel] = tf.math.ceil(
                probs - tf.random.uniform(probs.shape)
            )

def deprocess_image(x):
    # Stack the single channeled black and white image to RGB values.
    x = np.stack((x, x, x), 2)
    # Undo preprocessing
    x *= 255.0
    # Convert to uint8 and clip to the valid range [0, 255]
    x = np.clip(x, 0, 255).astype("uint8")
    return x

# Iterate over the generated images and plot them with matplotlib.
for i, pic in enumerate(pixels):
    keras.preprocessing.image.save_img(
        "generated_image_{}.png".format(i), deprocess_image(np.squeeze(pic, -1))
    )

display(Image("generated_image_0.png"))
display(Image("generated_image_1.png"))
display(Image("generated_image_2.png"))
display(Image("generated_image_3.png"))

  0%|          | 0/28 [00:00<?, ?it/s]

1/1 [==============================] - 0s 28ms/step


  4%|▎         | 1/28 [00:03<01:35,  3.54s/it]

1/1 [==============================] - 0s 114ms/step


  7%|▋         | 2/28 [00:06<01:17,  2.99s/it]

1/1 [==============================] - 0s 32ms/step


 11%|█         | 3/28 [00:08<01:08,  2.75s/it]

1/1 [==============================] - 0s 21ms/step


 14%|█▍        | 4/28 [00:10<01:00,  2.53s/it]

1/1 [==============================] - 0s 21ms/step


 18%|█▊        | 5/28 [00:12<00:52,  2.27s/it]

1/1 [==============================] - 0s 18ms/step


 21%|██▏       | 6/28 [00:14<00:44,  2.02s/it]

1/1 [==============================] - 0s 18ms/step


 25%|██▌       | 7/28 [00:15<00:39,  1.86s/it]

1/1 [==============================] - 0s 19ms/step


 29%|██▊       | 8/28 [00:17<00:35,  1.75s/it]

1/1 [==============================] - 0s 17ms/step


 32%|███▏      | 9/28 [00:18<00:32,  1.69s/it]

1/1 [==============================] - 0s 17ms/step


 36%|███▌      | 10/28 [00:20<00:29,  1.63s/it]

1/1 [==============================] - 0s 32ms/step


 39%|███▉      | 11/28 [00:22<00:30,  1.80s/it]

1/1 [==============================] - 0s 19ms/step


 43%|████▎     | 12/28 [00:24<00:28,  1.76s/it]

1/1 [==============================] - 0s 27ms/step


 46%|████▋     | 13/28 [00:25<00:25,  1.70s/it]

1/1 [==============================] - 0s 19ms/step


 50%|█████     | 14/28 [00:27<00:23,  1.67s/it]

1/1 [==============================] - 0s 20ms/step


 54%|█████▎    | 15/28 [00:28<00:21,  1.64s/it]

1/1 [==============================] - 0s 20ms/step


 57%|█████▋    | 16/28 [00:30<00:19,  1.63s/it]

1/1 [==============================] - 0s 18ms/step


 61%|██████    | 17/28 [00:32<00:17,  1.64s/it]

1/1 [==============================] - 0s 26ms/step


 64%|██████▍   | 18/28 [00:34<00:17,  1.72s/it]

1/1 [==============================] - 0s 31ms/step


 68%|██████▊   | 19/28 [00:35<00:15,  1.77s/it]

1/1 [==============================] - 0s 20ms/step


 71%|███████▏  | 20/28 [00:37<00:13,  1.71s/it]

1/1 [==============================] - 0s 18ms/step


 75%|███████▌  | 21/28 [00:39<00:11,  1.67s/it]

1/1 [==============================] - 0s 18ms/step


 79%|███████▊  | 22/28 [00:40<00:09,  1.64s/it]

1/1 [==============================] - 0s 18ms/step


 82%|████████▏ | 23/28 [00:42<00:08,  1.64s/it]

1/1 [==============================] - 0s 18ms/step


 86%|████████▌ | 24/28 [00:43<00:06,  1.63s/it]

1/1 [==============================] - 0s 30ms/step


 89%|████████▉ | 25/28 [00:45<00:05,  1.68s/it]

1/1 [==============================] - 0s 18ms/step


 93%|█████████▎| 26/28 [00:47<00:03,  1.81s/it]

1/1 [==============================] - 0s 19ms/step


 96%|█████████▋| 27/28 [00:49<00:01,  1.75s/it]

1/1 [==============================] - 0s 20ms/step


100%|██████████| 28/28 [00:50<00:00,  1.82s/it]
